---
title: "TF-IDF_PCA_Kmeans"
author: "呂羿賢"
date: "2018年8月7日"
output: html_document
---


```{r}
library(tm)
library(tmcn)
library(Matrix)
library(wordcloud)
library(FactoMineR)
library(factoextra)
```


```{r}
docs<-readLines("txt1.txt")
docs<-gsub("\\[[0-9]+\\]", "", docs)
docs.corpus <- Corpus(VectorSource(docs))
docs.seg<-tm_map(docs.corpus, segmentCN)
docs.tdm<-TermDocumentMatrix(docs.seg, control = list())

docs.tf<-apply(as.matrix(docs.tdm), 2, function(doc){doc/sum(doc)})
idf.function<-function(word_doc){log2((length(word_doc)+1)/nnzero(word_doc))}
docs.idf<-apply(docs.tdm, 1, idf.function)
docs.tfidf<-docs.tf*docs.idf

```

```{r}
docs<-readLines("txt1.txt")
docs<-gsub("\\[[0-9]+\\]", "", docs)
docs.corpus <- Corpus(VectorSource(docs))
docs.seg<-tm_map(docs.corpus, segmentCN)
docs.tdm<-TermDocumentMatrix(docs.seg, control = list())

docs.tf<-apply(as.matrix(docs.tdm), 2, function(doc){doc/sum(doc)})
idf.function<-function(word_doc){log2((length(word_doc)+1)/nnzero(word_doc))}
docs.idf<-apply(docs.tdm, 1, idf.function)
docs.tfidf<-docs.tf*docs.idf
```

```{r}
docs.pca <- prcomp(docs.tfidf, scale = T)
```

```{r}
fviz_eig(docs.pca, addlabels = TRUE, ylim = c(0, 10))
fviz_pca_ind(docs.pca, geom.ind = c("point"), col.ind = "cos2")
```


```{r}
fviz_pca_var(docs.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")
)
```

```{r}
fviz_pca_biplot(docs.pca, geom.ind = "point")
docs.eig <- get_eig(docs.pca)
docs.var <- get_pca_var(docs.pca)
docs.ind <- get_pca_ind(docs.pca)
```

```{r}
ind.coord2 <- docs.ind$coord[, 1:2]
wss <- c()
for (i in 1:10) { wss[i] <- kmeans(ind.coord2, i)$tot.withinss }
plot(wss, type = "b")
```

```{r}
km <- kmeans(ind.coord2, 3)
plot(ind.coord2, col = km$cluster)
points(km$centers, col = 1:3, pch = 8, cex = 2)
```